// Catálogo de presentes — fonte de verdade dos preços.
// O frontend só envia o "id"; o preço usado no pagamento vem sempre daqui.
export const PRODUTOS = {
  "aparelho-jantar-oxford": { nome: "Aparelho de Jantar/Chá Oxford Ryo Maresia 30 Peças", preco: 690.11 },
  "aspirador-vertical": { nome: "Aspirador de Pó Vertical", preco: 264.86 },
  "batedeira-philco": { nome: "Batedeira Philco Paris com 4 Velocidades - Branca", preco: 256.54 },
  "cama-box-colchao": { nome: "Cama box + colchão", preco: 4404.69 },
  "chaleira-eletrica": { nome: "Chaleira Elétrica Gourmand Gris 1,8L", preco: 278.71 },
  "colcha-casal-santista": { nome: "Colcha Casal Santista Boutis Dinis", preco: 504.61 },
  "conjunto-baixelas": { nome: "Conjunto de Baixelas Tramontina", preco: 466.77 },
  "conjunto-peneiras": { nome: "Conjunto de peneiras", preco: 230.23 },
  "conjunto-potes": { nome: "Conjunto de Potes Herméticos Redondos 4 peças", preco: 201.98 },
  "espelho-corpo": { nome: "Espelho De Corpo Inteiro", preco: 312.79 },
  "espelho-redondo": { nome: "Espelho Redondo 40 cm com Alça em Couro", preco: 401.68 },
  "faqueiro-42pcs": { nome: "Faqueiro - 42 Peças", preco: 682.92 },
  "grill-britania": { nome: "Grill Britânia Multi Grill", preco: 237.16 },
  "xicara-cafe-crystal": { nome: "Jogo com 6 Xícaras para Café com Pires modelo Crystal Chess", preco: 353.22 },
  "jogo-banho-buddemeyer": { nome: "Jogo de Banho Buddemeyer", preco: 426.29 },
  "jogo-cama-listrado": { nome: "Jogo de Cama Listrado", preco: 374.07 },
  "jogo-facas": { nome: "Jogo de Facas com Suporte em Madeira - 7 peças", preco: 526.33 },
  "jogo-panelas-preto": { nome: "Jogo de Panelas Preto - 5 Peças", preco: 990.26 },
  "jogo-xicaras-cafe": { nome: "Jogo de Xícaras para Café com Pires - 12 peças", preco: 359.40 },
  "jogo-edredom-cinza": { nome: "Jogo Edredom Casal Cinza - 3 Peças", preco: 657.89 },
  "jogo-toalha-azul": { nome: "Jogo Toalha de Banho Azul - 4 Peças", preco: 261.80 },
  "lavadora-secadora": { nome: "Lavadora e secadora de roupas", preco: 4466.29 },
  "liquidificador": { nome: "Liquidificador", preco: 327.17 },
  "lixo-cozinha": { nome: "Lixo para cozinha", preco: 265.73 },
  "mesa-jantar-4cadeiras": { nome: "Mesa de Jantar com 4 Cadeiras", preco: 3841.80 },
  "mixer-3em1": { nome: "Mixer 3 em 1 Vermelho", preco: 359.33 },
  "maquina-cafe-expresso": { nome: "Máquina de Café Expresso", preco: 449.85 },
  "panela-arroz-eletrica": { nome: "Panela de Arroz Elétrica", preco: 279.50 },
  "panela-pressao-eletrica": { nome: "Panela de Pressão Elétrica", preco: 499.18 },
  "porta-condimentos": { nome: "Porta Condimentos com Base Giratória em Madeira", preco: 230.23 },
  "processador-alimentos": { nome: "Processador de Alimentos Preto - 800W", preco: 466.77 },
  "rack": { nome: "Rack", preco: 512.28 },
  "robo-aspirador": { nome: "Robô Aspirador de Pó", preco: 1267.24 },
  "sanduicheira-mondial": { nome: "Sanduicheira Mondial Master Grill", preco: 221.92 },
  "smart-tv-43": { nome: "Smart TV LED 43 Polegadas", preco: 1787.90 },
  "sofa-retratil": { nome: "Sofá Retrátil Reclinável", preco: 3331.96 },
  "vaporizador-arno": { nome: "Vaporizador de Roupas Arno", preco: 281.58 },
  "ventilador-pe": { nome: "Ventilador de Pé", preco: 299.85 },
};
